# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-04 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='大类')),
            ],
        ),
        migrations.CreateModel(
            name='TypeShop2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='小类')),
                ('Fisrt_id', models.CharField(max_length=5, verbose_name='大类id')),
            ],
        ),
    ]
