# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-04 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeshop2',
            name='name',
            field=models.CharField(max_length=64, verbose_name='小类'),
        ),
    ]
