# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatDB', '0003_shopinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=256, verbose_name='商品简介')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('Image', models.ImageField(upload_to='', verbose_name='图片')),
            ],
        ),
    ]
