# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatDB', '0005_auto_20191004_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='price',
            field=models.FloatField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='price',
            field=models.FloatField(verbose_name='价格'),
        ),
    ]
