# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-06 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreatDB', '0007_auto_20191004_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': '商品详细信息', 'verbose_name_plural': '商品详细信息'},
        ),
        migrations.AlterModelOptions(
            name='shoplist',
            options={'verbose_name': '商品列表信息', 'verbose_name_plural': '商品列表信息'},
        ),
        migrations.AlterModelOptions(
            name='typeshop',
            options={'verbose_name': '商品大类', 'verbose_name_plural': '商品大类'},
        ),
        migrations.AlterModelOptions(
            name='typeshop2',
            options={'verbose_name': '商品小类', 'verbose_name_plural': '商品小类'},
        ),
    ]
