# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-07 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatDB', '0008_auto_20191006_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshop',
            name='group',
            field=models.IntegerField(default=0, verbose_name='组'),
        ),
    ]
